services:
  php-apache:
    build: .
    container_name: php-apache
    restart: unless-stopped

    env_file:
    - .env

    # Plus besoin d'exposer le port publiquement, Nginx s'en charge
    expose:
      - "80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - web         # ← accessible par Nginx
      - site_internal

  mysql:
    image: mysql:8.0
    container_name: site-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - site_internal   # ← jamais exposé à l'extérieur

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8083:80"   # ← accessible uniquement en local (SSH/WireGuard)
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - site_internal

networks:
  web:
    external: true        # ← réseau partagé avec Nginx
  site_internal:
    driver: bridge        # ← réseau interne, mysql jamais exposé

volumes:
  mysql_data:
